CREATE TABLE 
    IS601_Genres (
        id INT PRIMARY KEY AUTO_INCREMENT,
        genre_name VARCHAR(100) NOT NULL UNIQUE CHECK (genre_name <> ''),
        created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );